# Basic agent information
agent:
  name: support_agent
  description: "Agent that helps McDonald's customers report order/visit issues, leave feedback, and get answers to FAQs by calling backend tools as needed"

# MCP server connections
connections:
  mcp_servers:
    - name: mock_api_server

configuration:
  llm:
    model_group: openai-gpt-5-1-reasoning
  prompt_template: sub_agents/support_agent/prompt_template.jinja2
  enable_filler_messages: false
